{
 "title": "ReViSE",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Nombre de lobby créés",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(lobby_created_counter_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de parties rejointes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(lobby_joined_counter_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de parties commencées",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(lobby_started_counter_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre d'erreurs serveurs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(logback_events_total{level=\"error\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tendance de la création de lobby",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(lobby_created_counter_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tendance des parties commencées",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "round(increase(lobby_started_counter_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tendance des parties supprimées",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "round(increase(lobby_cleared_counter_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tendance des parties terminées",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {}
   ]
  }
 ]
}